#ifndef _ARCH_DRIVERS_MAILBOX_H
#define _ARCH_DRIVERS_MAILBOX_H

#include <arch/mmio.h>

#include <stdint.h>

#define VIDEOCORE_MAILBOX (MMIO_BASE + 0xB880)
#define MAILBOX_READ (VIDEOCORE_MAILBOX)
#define MAILBOX_POLL (VIDEOCORE_MAILBOX + 0x10)
#define MAILBOX_SENDER (VIDEOCORE_MAILBOX + 0x14)
#define MAILBOX_STATUS (VIDEOCORE_MAILBOX + 0x18)
#define MAILBOX_CONFIG (VIDEOCORE_MAILBOX + 0x1C)
#define MAILBOX_WRITE (VIDEOCORE_MAILBOX + 0x20)
#define MAILBOX_RESPONSE (0x80000000)
#define MAILBOX_FULL (0x80000000)
#define MAILBOX_EMPTY (0x40000000)

uint32_t mailbox_call(uint8_t c);

#endif /* _ARCH_DRIVERS_MAILBOX_H */
