/*++
Module Name:  axboot.h
Project:      AurixOS

Copyright (c) 2024 Jozef Nagy

This source is subject to the MIT License.
See License.txt in the root of this repository.
All other rights reserved.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
--*/

#ifndef _AXBOOT_H
#define _AXBOOT_H

#include <aurixos.h>

#include <efi.h>

#define AXBOOT_VERSION_STR L"0.1"
#define AXBOOT_COPYRIGHT_STR L"(c) 2024 Jozef Nagy"

EXTERN EFI_HANDLE g_ImageHandle;
EXTERN EFI_SYSTEM_TABLE *g_SystemTable;

typedef ULONG AXBOOT_STATUS;

#endif /* _AXBOOT_H */
